# Generated by Django 4.2.3 on 2023-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
